PresenceCMAOptions:
    ConnectionString: data source=.;initial catelog=Presence_QA;User ID=sa;Password=P@ssw0rd;Persist Security=False;
    CacheNewsKey: cma_news_cache
    CachePeopleKey: cma_people_cache
    CacheEventKey: cma_event_cache
    CacheSchoolKey: cma_school_cache